version: '3.8'

services:
  dnd-battlemap:
    image: thetemplar/dnd-battlemap:latest
    container_name: dnd-battlemap
    ports:
      - "4000:3000"
    volumes:
      # Mount persistent data directories
      - ./data/adventures:/app/adventures
      - ./data/uploads:/app/uploads
      - ./data/tokens:/app/tokens
      - ./data/maps:/app/maps
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 